services:
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      retries: 5
      start_period: 5s

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  bakend:
    build: ./backend
    container_name: backend
    restart: always
    depends_on:
      - mongodb
      - rabbitmq
    ports:
      - "5000:5000"
    networks:
      - my_network
    environment:
      - MONGO_URI = mongodb://mongo:27017/transactions


  frontend:
    build: ./frontend
    container_name: frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "5173-5173"
    networks:
      - my_network

volumes:
  mongodb_data: